dogcat/urls.py
from django.urls import path

from . import views

app_name ='dogcat'
urlpatterns = [
    path('', views.top_page, name='top_page'),
    path('dogcat/', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

lovery_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogcat.urls')),
    path('dogcat/', include('dogcat.urls')),
]

dogcat/models.py
from django.db import models

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64

graph = tf.compat.v1.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224 # 画像サイズ
    MODEL_FILE_PATH = './dogcat/ml_models/vgg16_transfer.h5' 
    classes = ["犬", "猫"]
    num_classes = len(classes)

    # 引数から画像ファイルを参照して読み込む
    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

dogcat/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

dogcat/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def top_page(request):
    template = loader.get_template('dogcat/top_page.html')
    context = {}
    return HttpResponse(template.render(context, request))

def index(request):
    template = loader.get_template('dogcat/index.html')
    context = {'form': PhotoForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('dogcat:index')

    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    predicted, percentage = photo.predict()

    template = loader.get_template('dogcat/result.html')

    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predicted,
        'percentage': percentage,
    }

    return HttpResponse(template.render(context, request))

dogcat/templates/dogcat/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dogcat/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>LOVERY BOT | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'dogcat:top_page' %}">LOVERY BOT</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

dogcat/templates/dogcat/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dogcat/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>LOVERY BOT | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'dogcat:top_page' %}">LOVERY BOT</a>
    </nav>
    <div class="dogandcat-image">
    <div class="container">
        <div>
    <h4 class="mt-4 mb-5 border-bottom">犬・猫判定</h4>
    <p>画像ファイルを選択して推定ボタンをクリックしてください。</p>
        <form action="{% url 'dogcat:predict' %}" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="custom-file">
                {{ form.image }}
                <label class="custom-file-label" for="customFile">
                    推定したいファイルを選択してください。
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">推定する！</button>
    </form> 
</div>
    </div>
    </div>
</body>
</html>

dogcat/templates/dogcat/result.html
{% extends 'dogcat/base.html' %}
{% block title %}推定結果{% endblock %}

{% block content %}
<div>
    <table class='table'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ photo_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class='preview-img' src={{ photo_data }} ></img></td>
                </tr>
            <tr class="dogcat_answer">
                <td>推定結果</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr class="dogcat_percentage">
                <td>確率</td>
                <td>{{ percentage }} %</td>
            </tr>
        </tbody>
    </table>

    <a href = "{% url 'dogcat:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>

</div>
{% endblock %}

dogcat/templates/dogcat/top_page.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dogcat/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>LOVERY BOT | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'dogcat:top_page' %}">LOVERY BOT</a>

    </nav>
    <div class="top-content">
        <div class="select-content">
            <div>
                <a class="dogcat-link" href="{% url 'dogcat:index' %}">LOVERY EYE</a><br>
                <p class="dogcat-introduction">一枚の画像を判定し、写っているのが犬か猫かを予想します。</p>
            </div>
                    
            
            
            <div>
                <a class="draw-link" href="https://h-funase.github.io/">LOVERY DRAW</a><br>
                <p class="draw-introduction">二枚の画像を合成し、新しい画像を作り出します。</p>
            </div>
        </div>
        <div class="bot-top-page"></div> 
    </div>
</body>
</html>